# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ 'linux', 'windows' ]
        goarch: [ 'amd64' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'
    
    - name: Install dependencies
      run: go get .
      
    - name: Build
      run: CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o a.out .

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: Binary-${{ matrix.goos }}-${{ matrix.goarch }}
        path: a.out
